# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67decc1defe03a6a503765301b25ab404a9c4d21b8a94e2a68f8ddfe8c0634c0a1c2c8e98398c6e6ae02eb5837e586a877ed67e00426eea7c037ae3eb7fd6ae7

test:
  secret_key_base: 64e4290f87d831f6536926bd906e38d3f794067eb00b93a8eb012ffd92d159ae284951f83a953aa1e1b717d2c64a52342e74447d801ef6e30cf8b78f018c07d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
